### ISSUE TITLE
HttpRequestExecuterExceptionMessageBuilder 中的日志 ConnectionConfig 如果是 null 值忽略输出

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-net#69]
HttpRequestExecuterExceptionMessageBuilder 中的日志 ConnectionConfig 如果是 null 值忽略输出

```JAVA

com.feilong.net.UncheckedHttpException: httpRequest:[    {
        "fullEncodedUrl": "http://www.XXXX.cn/itemRecommand/XXXXX?category_code=null&XXXXX=BESTSELLER_TYPE",
        "requestBody": "",
        "httpMethodType": "GET",
        "paramMap": null,
        "headerMap": null,
        "uri": "http://www.XXX.cn/XXX/XXXXX?category_code=null&recommandType=XXXXX"
    }],useConnectionConfig:[    {
        "turnOffHostnameVerifier": true,
        "readTimeout": 20000,
        "connectTimeout": 20000,
        "proxyAddress": "",
        "userName": "",
        "proxyPort": null,
        "password": "",
        "contentCharset": "UTF-8"
    }],cause by:[java.lang.NullPointerException]
	at com.feilong.net.httpclient4.builder.HttpRequestExecuter.execute(HttpRequestExecuter.java:64)
	at com.feilong.net.httpclient4.HttpClientUtil.getResponseBodyAsString(HttpClientUtil.java:985)
	at com.feilong.net.httpclient4.HttpClientUtil.getResponseBodyAsString(HttpClientUtil.java:893)

```

此处的 json , 比如 proxy 如果没有传值  可以不输出

```JSON

useConnectionConfig:[    {
        "turnOffHostnameVerifier": true,
        "readTimeout": 20000,
        "connectTimeout": 20000,
        "proxyAddress": "",
        "userName": "",
        "proxyPort": null,
        "password": "",
        "contentCharset": "UTF-8"
    }]

```

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/64323715-92e71400-cff7-11e9-93a0-dd1d977e6e75.png)
