### ISSUE TITLE
java.lang.IllegalArgumentException: session must Connected

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-net#74]
```JAVA

[2019-10-24 18:20:06:031 CST] ERROR com.ba.store.manager.ami.sync.file.SyncOnlineItemsInfoToSftpManagerImpl.synOnlineItemInfoToSftp(SyncOnlineItemsInfoToSftpManagerImpl.java:102) : write product info to csv file failed!!!,message={}
java.lang.IllegalArgumentException: session must Connected
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at com.feilong.net.filetransfer.sftp.SftpSessionUtil.buildSessionPrettyString(SftpSessionUtil.java:51)
	at com.feilong.net.filetransfer.sftp.SFTPFileTransfer.disconnect(SFTPFileTransfer.java:165)
	at com.feilong.net.filetransfer.sftp.SFTPFileTransfer.connect(SFTPFileTransfer.java:105)
	at com.feilong.net.filetransfer.AbstractFileTransfer.upload(AbstractFileTransfer.java:104)
	at com.bz.store.manager.ami.sync.file.SyncOnlineItemsInfoToSftpManagerImpl.synOnlineItemInfoToSftp(SyncOnlineItemsInfoToSftpManagerImpl.java:90)
	at com.bz.store.manager.ami.sync.file.SyncOnlineItemsInfoToSftpManagerImpl.syncOnlineItemsInfo(SyncOnlineItemsInfoToSftpManagerImpl.java:72)
	at sun.reflect.GeneratedMethodAccessor834.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy540.syncOnlineItemsInfo(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:312)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)


```

**Comment by venusdrogon** [comment]
到了这里 session 可能某些原因 是 null

![image](https://user-images.githubusercontent.com/3479472/67481872-4a61e380-f695-11e9-92f7-ad7023837c73.png)
