### ISSUE TITLE
HttpRequestExecuter.execute(HttpRequest, ConnectionConfig) 需要显示的abort httpUriRequest

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-net#80]
HttpRequestExecuter.execute(HttpRequest, ConnectionConfig) 需要显示的关闭 httpUriRequest

不管是执行成功还是出现了异常

如果不abort , 那么在复用httpclient 的情况下, 以下代码会出现, 不能从连接池中拿链接的情况 

![image](https://user-images.githubusercontent.com/3479472/75148479-b5522280-573a-11ea-9376-687d15045851.png)

![image](https://user-images.githubusercontent.com/3479472/75148522-cbf87980-573a-11ea-8d0c-62a714bca95c.png)

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/75223411-5e535880-57e1-11ea-8195-d634b697fdd4.png)

![image](https://user-images.githubusercontent.com/3479472/75223429-68755700-57e1-11ea-997c-60200da4ed55.png)

不能简单直接的关闭, 否则取内容的地方会报错  java.net.SocketException: Socket is closed


```
com.feilong.net.UncheckedHttpException: java.net.SocketException: Socket is closed
	at com.feilong.net.httpclient4.builder.HttpResponseUtil.getResultString(HttpResponseUtil.java:62)
	at com.feilong.net.httpclient4.HttpClientUtil.getResponseBodyAsString(HttpClientUtil.java:986)
	at com.feilong.net.httpclient4.HttpClientUtil.getResponseBodyAsString(HttpClientUtil.java:893)
	at com.feilong.net.httpclient4.HttpClientUtil.get(HttpClientUtil.java:597)

````
